# Generated by Django 3.2 on 2022-07-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_description'),
        ('request', '0002_request_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, default='leggings', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
