# Generated by Django 3.2 on 2022-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
