# Generated by Django 3.2 on 2022-07-27 13:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('small', 'Small'), ('medium', 'Medium')], max_length=12),
        ),
    ]
