# Generated by Django 3.2 on 2022-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='ready_to_ship',
            field=models.BooleanField(default=False),
        ),
    ]
