# Generated by Django 3.2 on 2022-07-27 13:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220727_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('6-9m', '6-9 months'), ('9-12m', '9-12 months'), ('12-18m', '12-18 months'), ('18-24m', '18-24 months'), ('2-3y', '2-3 years'), ('3-4y', '3-4 years'), ('4-5y', '4-5 years'), ('5-6y', '5-6 years'), ('6-7y', '6-7 years'), ('7-8y', '7-8 years'), ('8-9y', '8-9 years'), ('9-10y', '9-10 years')], max_length=65),
        ),
    ]
